### ISSUE TITLE
Missing pom dependencies

### ISSUE THREAD

**Issue by seliver** [rogargon/redefer#1]
Just to mention that /src/main/resources/lib/ folder is missing. 
Some other includes are also necessary no update as maven doesn't detect them.

**Comment by rogargon** [comment]
Sorry, the ReDeFer project is now being reworked as a set of separate GitHub repositories, one for each tool. Currently updated versions are available for RDF2HTML and RDF2SVG as described in README.md
Working now on updated versions for XML2RDF and XSD2OWL, which will fix the missing dependencies issues.
